name: Deploy to GitHub pages

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy-ghpage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install & Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build:gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: dist
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
